### ISSUE TITLE
Upload coverage report of all go modules

### ISSUE THREAD

**Issue by masih** [protocol/.github#136]
If a go repo has multiple modules, it seems only the coverage for root module is uploaded. It would be fantastic to get coverage for all modules uploaded to codecov. 

Example:

`go-car` has [a module in root](https://github.com/ipld/go-car/blob/master/go.mod) and one in [v2](https://github.com/ipld/go-car/blob/master/v2/go.mod). But only the root module coverage shows up on [codecov](https://app.codecov.io/gh/ipld/go-car/).

**Comment by mvdan** [comment]
We should look at whether the codecov action allows uploading many files, i.e. one per module.

If it does not, then perhaps our best bet is to merge all coverage files into one (with a tool like https://github.com/wadey/gocovmerge), and upload that.

**Comment by marten-seemann** [comment]
The Codecov Action allows that via the `files` option: https://github.com/codecov/codecov-action#arguments.

The hard thing is populating this value. I remember playing around with this a while back, but running into all kinds of problems. The easy way to do this would be the following:
```yml
env:
    COVERAGES: ""
steps:
    - test:
      run:
          for dir in dirs; do
                # append to COVERAGES
          done
    - uses: codecov/codecov-action@v2
      with:
         files: ${{ env.COVERAGES }}
```

Unfortunately, this doesn't work, since we're using the [multiple-go-modules](https://github.com/protocol/multiple-go-modules) action, which doesn't allow us to access environment variables from the environment we're running in (which makes a lot of sense from a security perspective).

One option would be to modify the multiple-go-modules such that it takes input variables and exports an output variable, analogous to https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action#creating-an-action-metadata-file.

The other option, as @mvdan suggested, would be to merge coverage files while we create them. Since `gocovmerge` also needs a list of files, we'd probably have to perform the merge incrementally, as soon as we've finished processing one module. Or we could just combine all `**/coverage.txt`, and hope that the repo didn't come with any `coverage.txt` files that are not actually coverage reports.
