### ISSUE TITLE
Increase go-test timeout to 30m

### ISSUE THREAD

**Issue by galargh** [protocol/.github#226]
There are repositories which have long-running tests that exceed the default 10m timeout. The suggestion here is to increase the global timeout to 30m (see https://github.com/ipfs/go-ds-crdt/pull/123#issuecomment-971412819 for details).

Right now one way to increase a timeout in a particular repository is to add a custom `go-test-setup` action in that repository that looks something like that:
```
name: extend-tests-timeout
description: add -timeout 20m flag to GOFLAGS to extend timeout for tests

runs:
  using: "composite"
  steps:
    - name: Extend timeout for tests
      shell: bash
      run: echo "GOFLAGS=$GOFLAGS -timeout=20m" >> $GITHUB_ENV
```

In my opinion, we shouldn't increase the default timeout. Here are some reasons why:
- by keeping the default timeout low we encourage test optimisation;
- we keep the feedback loop smaller. For (extreme) example, if someone writes a test that hangs forever they'd receive feedback in 10 minutes rather than 30 minutes proposed here;
- the timeout itself acts as a guard for introduction of long-running tests.

So maybe instead we could think of a better way (than the one mentioned above) to override the default timeout on a per-repo basis.
